server:
  port: ${PORT:0}

spring:
  application:
    name: ATM-SERVICE
  session:
    store-type: redis
  redis:
    url: localhost
    port: 6379

springdoc:
  swagger-ui:
    path: /swagger-ui.html